icon: assets/icons/icon.png
summary: An application to stream Music
group: Application/Multimedia
vendor: fncshaolin
packager: fncshaolin
license: GPLv3
url: https://github.com/fncshaolin/elythra

requires:
  - mpv-libs
  - libappindicator

display_name: Elythra

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music

startup_notify: true