name: Android Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build debug APK
      run: |
        cd android
        ./gradlew assembleUniversalDebug
        
    - name: Build release APK (unsigned)
      run: |
        cd android
        ./gradlew assembleUniversalRelease
      continue-on-error: true
      
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: elythra-debug-apk
        path: android/app/build/outputs/apk/universal/debug/*.apk
        
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: elythra-release-apk
        path: android/app/build/outputs/apk/universal/release/*.apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download APKs
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          elythra-debug-apk/*.apk
          elythra-release-apk/*.apk
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}